/**
 * Canonical Produce Marketplace catalogue.
 *
 * Single source of truth, consumed two ways:
 *   - `admin.seed.js` re-exports it as `initialMarketplaceAdminListings`, so
 *     the full `npm run seed` inserts exactly this set (delete-then-insert).
 *   - `marketplace.seed.js` upserts it by `produceName` under
 *     `npm run seed:marketplace`, which does NOT touch any other collection
 *     and is safe to re-run against a live database.
 *
 * Field names follow the flat DB vocabulary that `admin.mappers.js` already
 * renders. The marketplace module maps them onto the frontend's
 * `ProduceListing` shape (`cropName`, `quantityKg`, `pricePerKgBdt`, ...).
 *
 * `id` is a readable seed key only — `strip()` removes it before insert, so
 * it never reaches MongoDB.
 *
 * `ownerEmail` is a marker for the same reason: `resolveListingOwners()`
 * (see `marketplace.owners.js`) turns it into the `owner` ObjectId at run time
 * and drops it from the payload. A hard-coded ObjectId would break the moment
 * `npm run seed` recreated the users, and without an owner a listing is
 * invisible to the seller portal's My Listings and to `GET /orders/sales` —
 * which is how the shelf looked empty even though the catalogue was full.
 *
 * Split across both demo sellers so each portal starts with a shelf, and
 * spread over every moderation status so the admin gate has real records to
 * act on: farmer gets Approved / Pending Review / Flagged / Rejected, supplier
 * gets Approved / Pending Review.
 */

const ART = "/produce"; // served from FarmPath/public/produce

const listings = [
  // ── existing admin-moderation records (kept verbatim) ────────────
  {
    id: "LIST-401",
    ownerEmail: "farmer@demo.com",
    farmerName: "Mohiuddin Khan",
    farmerPhone: "+880 1712-449821",
    produceName: "Boro Rice (BRRI-28)",
    variety: "Clean Milled Long Grain",
    category: "Cereal Grains",
    quantityAvailableKg: 8500,
    askingPricePerKg: 32.5,
    suggestedFloorPrice: 30,
    suggestedCeilingPrice: 34,
    qualityGrade: "Grade A",
    locationHub: "Bogura Central Agritech Silo Hub",
    district: "Bogura",
    status: "Approved",
    listedDate: "2026-09-12",
    harvestDate: "2026-08-28",
    availableUntil: "2026-11-30",
    minimumOrderKg: 100,
    isVerified: true,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkX1QyxEfc3HETNvljYNm0vWcgZL3rCL7rIIKBROdPVjRW3e9smRBV2Tum&s=10",
    description:
      "Machine-harvested Boro paddy, sun-dried to 12% moisture and stored at the Bogura silo hub. Uniform long grain with low broken percentage.",
    tags: ["paddy", "boro", "irrigated"],
  },
  {
    id: "LIST-402",
    ownerEmail: "farmer@demo.com",
    farmerName: "Farhana Parveen",
    farmerPhone: "+880 1622-441199",
    produceName: "Winter Potato (Diamant)",
    variety: "Grade 1 Processing",
    category: "Tubers & Vegetables",
    quantityAvailableKg: 14000,
    askingPricePerKg: 19,
    suggestedFloorPrice: 16.5,
    suggestedCeilingPrice: 20.5,
    qualityGrade: "Grade A",
    locationHub: "Mymensingh Cold Complex Hub",
    district: "Mymensingh",
    status: "Approved",
    listedDate: "2026-09-14",
    harvestDate: "2026-09-01",
    availableUntil: "2026-12-15",
    minimumOrderKg: 200,
    isVerified: true,
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop",
    description:
      "Cold-stored Diamant seed stock with consistent tuber size. Suitable for both fresh market and chipping-grade processing.",
    tags: ["potato", "cold-stored", "winter"],
  },
  {
    id: "LIST-403",
    ownerEmail: "farmer@demo.com",
    farmerName: "Anisur Rahman",
    farmerPhone: "+880 1733-112233",
    produceName: "Yellow Feed Maize",
    variety: "Pacific 999 High Starch",
    category: "Animal Feed Grain",
    quantityAvailableKg: 22000,
    askingPricePerKg: 28,
    suggestedFloorPrice: 26,
    suggestedCeilingPrice: 30,
    qualityGrade: "Grade B",
    locationHub: "Dinajpur Grain Terminal",
    district: "Dinajpur",
    status: "Pending Review",
    listedDate: "2026-09-16",
    harvestDate: "2026-09-05",
    availableUntil: "2026-12-31",
    minimumOrderKg: 500,
    isVerified: false,
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&auto=format&fit=crop",
    description:
      "High-starch yellow maize for poultry and cattle feed. Awaiting moisture re-test before release to buyers.",
    tags: ["maize", "feed", "high-starch"],
  },
  {
    id: "LIST-404",
    ownerEmail: "farmer@demo.com",
    farmerName: "Jasim Hossain",
    farmerPhone: "+880 1552-881920",
    produceName: "Raw Jute Fibers",
    variety: "Tossa High Sheen",
    category: "Cash Crops",
    quantityAvailableKg: 6500,
    askingPricePerKg: 110,
    suggestedFloorPrice: 85,
    suggestedCeilingPrice: 95,
    qualityGrade: "Grade C",
    locationHub: "Natore Trading Mandi",
    district: "Natore",
    status: "Flagged",
    listedDate: "2026-09-10",
    harvestDate: "2026-08-14",
    availableUntil: "2026-10-31",
    minimumOrderKg: 50,
    isVerified: false,
    imageUrl: "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=800&auto=format&fit=crop",
    description:
      "Retted tossa jute with good lustre. Flagged pending a root-level grading re-inspection of this consignment.",
    tags: ["jute", "tossa", "fiber"],
  },

  // ── additional catalogue (marketplace browse) ────────────────────
  {
    id: "LIST-405",
    ownerEmail: "farmer@demo.com",
    farmerName: "Rahima Begum",
    farmerPhone: "+880 1815-776620",
    produceName: "Mung Bean (Moog)",
    variety: "BARI Mung-6",
    category: "Pulses",
    quantityAvailableKg: 3200,
    askingPricePerKg: 96,
    suggestedFloorPrice: 88,
    suggestedCeilingPrice: 104,
    qualityGrade: "Grade A",
    locationHub: "Rangpur Pulse Collection Centre",
    district: "Rangpur",
    status: "Approved",
    listedDate: "2026-09-18",
    harvestDate: "2026-09-02",
    availableUntil: "2027-01-20",
    minimumOrderKg: 25,
    isVerified: true,
    imageUrl: "https://www.mpbmsma.org/wp-content/uploads/2019/09/maung-bean767x511.jpg",
    description:
      "Hand-cleaned mung beans, machine-graded and double-winnowed. Consistent size with no weevil damage.",
    tags: ["mung", "pulse", "protein"],
  },
  {
    id: "LIST-406",
    ownerEmail: "supplier@demo.com",
    farmerName: "Shafiqul Islam",
    farmerPhone: "+880 1911-340027",
    produceName: "Mustard Seeds",
    variety: "BARI Sharisha-14",
    category: "Oilseeds",
    quantityAvailableKg: 5400,
    askingPricePerKg: 74,
    suggestedFloorPrice: 68,
    suggestedCeilingPrice: 82,
    qualityGrade: "Grade A",
    locationHub: "Jessore Oilseed Crushing Yard",
    district: "Jashore",
    status: "Approved",
    listedDate: "2026-09-19",
    harvestDate: "2026-08-30",
    availableUntil: "2026-12-20",
    minimumOrderKg: 100,
    isVerified: true,
    imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop",
    description:
      "High-oil-content mustard seed at 41% extraction rate. Ideal for local crushing mills and oil expellers.",
    tags: ["mustard", "oilseed", "crushing"],
  },
  {
    id: "LIST-407",
    ownerEmail: "farmer@demo.com",
    farmerName: "Nasrin Akter",
    farmerPhone: "+880 1644-908813",
    produceName: "Himsagar Mango",
    variety: "Rajshahi Orchard Grade",
    category: "Fruits",
    quantityAvailableKg: 2800,
    askingPricePerKg: 128,
    suggestedFloorPrice: 115,
    suggestedCeilingPrice: 145,
    qualityGrade: "Grade A",
    locationHub: "Rangpur Agri Produce Collection Centre",
    district: "Rajshahi",
    status: "Approved",
    listedDate: "2026-09-20",
    harvestDate: "2026-07-18",
    availableUntil: "2026-10-18",
    minimumOrderKg: 20,
    isVerified: true,
    imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop",
    description:
      "Naturally ripened Himsagar with high Brix and fibre-free flesh. Packed in ventilated crates for transit.",
    tags: ["mango", "himsagar", "fresh"],
  },
  {
    id: "LIST-408",
    ownerEmail: "supplier@demo.com",
    farmerName: "Abdul Karim",
    farmerPhone: "+880 1777-551204",
    produceName: "BRRI dhan-71 Paddy",
    variety: "Late Season Aus",
    category: "Cereal Grains",
    quantityAvailableKg: 9600,
    askingPricePerKg: 30,
    suggestedFloorPrice: 28,
    suggestedCeilingPrice: 33,
    qualityGrade: "Grade B",
    locationHub: "Cumilla Rice Mill Cluster",
    district: "Cumilla",
    status: "Approved",
    listedDate: "2026-09-21",
    harvestDate: "2026-09-08",
    availableUntil: "2026-12-10",
    minimumOrderKg: 250,
    isVerified: false,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop",
    description:
      "Late-season aus paddy with good milling recovery. Awaiting third-party residue certification.",
    tags: ["paddy", "aus", "milling"],
  },
  {
    id: "LIST-409",
    ownerEmail: "farmer@demo.com",
    farmerName: "Mizanur Rahman",
    farmerPhone: "+880 1521-663390",
    produceName: "Onion (B_paree)",
    variety: "BPI Agree-1",
    category: "Tubers & Vegetables",
    quantityAvailableKg: 11500,
    askingPricePerKg: 46,
    suggestedFloorPrice: 42,
    suggestedCeilingPrice: 52,
    qualityGrade: "Grade A",
    locationHub: "Pabna Vegetable Wholesale Hub",
    district: "Pabna",
    status: "Approved",
    listedDate: "2026-09-22",
    harvestDate: "2026-08-22",
    availableUntil: "2027-02-28",
    minimumOrderKg: 150,
    isVerified: true,
    imageUrl: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop",
    description:
      "Cured and neck-trimmed onion with tight scales. Stores well through the rabi season in ventilated bags.",
    tags: ["onion", "cured", "storage"],
  },
  {
    id: "LIST-410",
    ownerEmail: "farmer@demo.com",
    farmerName: "Selina Yasmin",
    farmerPhone: "+880 1739-224471",
    produceName: "Chickpeas (Booter Chola)",
    variety: "Desi Brown",
    category: "Pulses",
    quantityAvailableKg: 4100,
    askingPricePerKg: 88,
    suggestedFloorPrice: 80,
    suggestedCeilingPrice: 95,
    qualityGrade: "Grade B",
    locationHub: "Bogura Pulse Collection Centre",
    district: "Bogura",
    status: "Approved",
    listedDate: "2026-09-23",
    harvestDate: "2026-08-19",
    availableUntil: "2027-01-31",
    minimumOrderKg: 50,
    isVerified: false,
    imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=800&auto=format&fit=crop",
    description:
      "Air-dried desi chickpeas at 10% moisture. Ready for milling or direct retail packing.",
    tags: ["chickpea", "pulse", "desi"],
  },
  {
    id: "LIST-411",
    ownerEmail: "supplier@demo.com",
    farmerName: "Kamal Poddar",
    farmerPhone: "+880 1688-714405",
    produceName: "Sesame Seeds (Til)",
    variety: "White Til",
    category: "Oilseeds",
    quantityAvailableKg: 1800,
    askingPricePerKg: 165,
    suggestedFloorPrice: 150,
    suggestedCeilingPrice: 180,
    qualityGrade: "Grade A",
    locationHub: "Jamalpur Oilseed Collection Point",
    district: "Jamalpur",
    status: "Pending Review",
    listedDate: "2026-09-24",
    harvestDate: "2026-09-11",
    availableUntil: "2026-12-31",
    minimumOrderKg: 20,
    isVerified: false,
    imageUrl: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop",
    description:
      "Float-cleaned white sesame with low extraneous matter. Awaiting grade confirmation before release.",
    tags: ["sesame", "til", "oilseed"],
  },
  {
    id: "LIST-412",
    ownerEmail: "farmer@demo.com",
    farmerName: "Habibur Rahman",
    farmerPhone: "+880 1955-803312",
    produceName: "Sugarcane (JW-76)",
    variety: "High Recovery",
    category: "Cash Crops",
    quantityAvailableKg: 48000,
    askingPricePerKg: 7.5,
    suggestedFloorPrice: 6.8,
    suggestedCeilingPrice: 8.4,
    qualityGrade: "Grade C",
    locationHub: "Kushtia Sugar Mill Gate",
    district: "Kushtia",
    status: "Rejected",
    listedDate: "2026-09-09",
    harvestDate: "2026-09-01",
    availableUntil: "2026-10-31",
    minimumOrderKg: 1000,
    isVerified: false,
    imageUrl: "https://images.unsplash.com/photo-1527847263472-aa5338d178b8?w=800&auto=format&fit=crop",
    description:
      "High-recovery cane delivered direct to the mill gate. Rejected — scheduling conflict with the current crushing run.",
    tags: ["sugarcane", "mill-grade"],
  },
];

module.exports = { listings, ART };
