/**
 * Quality inspection fixtures — MARKETPLACE_PORTAL_PLAN Step 5.
 *
 * Eight assignments for the demo inspector, split across the workflow so every
 * inspector screen has something to show on a fresh database:
 *
 *   3 × `assigned`     waiting in the queue, already scheduled
 *   2 × `in_progress`  started but not yet submitted
 *   3 × `completed`    carry measurements, a verdict and a certificate number,
 *                      so the Reports page and the admin quality list agree
 *
 * `batchCode` is the natural key the seeder upserts on. Dates are written as
 * plain `YYYY-MM-DD` strings because that is what `mapScheduleEntry` and the
 * frontend's date pickers consume — there is no `Date` field to format.
 *
 * `owner` is intentionally absent: it is resolved at seed time from
 * `inspector@demo.com`, because a hard-coded ObjectId would not survive a
 * `npm run seed`.
 */
const inspections = [
  {
    batchCode: "HB-2026-014",
    produceType: "Onion",
    farmerName: "Jamal Hossain",
    farmerPhone: "+880 1711 204511",
    farmLocation: "Jessore, Jashore Sadar",
    variety: "Atlas Hybrid",
    quantityKg: 850,
    testingLabLocation: "Jessore Post-Harvest Lab",
    requestedAt: "2026-10-01",
    scheduledDate: "2026-10-06",
    status: "assigned",
    priority: "urgent",
    notes: "Buyer requested an aflatoxin reading before releasing escrow.",
  },
  {
    batchCode: "HB-2026-015",
    produceType: "Paddy Rice",
    farmerName: "Mohiuddin Khan",
    farmerPhone: "+880 1812 330470",
    farmLocation: "Bogura, Shibganj",
    variety: "BRRI dhan-28",
    quantityKg: 2400,
    testingLabLocation: "Bogura Regional Grain Testing Lab",
    requestedAt: "2026-10-01",
    scheduledDate: "2026-10-08",
    status: "assigned",
    priority: "normal",
    notes: "Moisture check on the second drying pass.",
  },
  {
    batchCode: "HB-2026-016",
    produceType: "Potato",
    farmerName: "Rina Begum",
    farmerPhone: "+880 1915 774120",
    farmLocation: "Munshiganj, Sirajdikhan",
    variety: "Diamant",
    quantityKg: 3200,
    testingLabLocation: "Munshiganj Cold Store Lab",
    requestedAt: "2026-10-02",
    scheduledDate: "2026-10-13",
    status: "assigned",
    priority: "normal",
    notes: "Grading for a cold-storage contract renewal.",
  },
  {
    batchCode: "HB-2026-011",
    produceType: "Mango",
    farmerName: "Abdul Karim",
    farmerPhone: "+880 1677 901234",
    farmLocation: "Rajshahi, Bagha",
    variety: "Himsagar",
    quantityKg: 620,
    testingLabLocation: "Rajshahi Fruit Testing Cell",
    requestedAt: "2026-09-27",
    scheduledDate: "2026-10-03",
    status: "in_progress",
    priority: "normal",
    notes: "Sugars are borderline; re-test after one more ripening day.",
  },
  {
    batchCode: "HB-2026-012",
    produceType: "Chilli",
    farmerName: "Sefat Ullah",
    farmerPhone: "+880 1521 668890",
    farmLocation: "Bogura, Kahaloo",
    variety: "Bijoli",
    quantityKg: 310,
    testingLabLocation: "Bogura Regional Grain Testing Lab",
    requestedAt: "2026-09-28",
    scheduledDate: "2026-10-02",
    status: "in_progress",
    priority: "urgent",
    notes: "Colour and stem-rot screening before grading.",
  },
  {
    batchCode: "HB-2026-003",
    produceType: "Paddy Rice",
    farmerName: "Nurul Islam",
    farmerPhone: "+880 1733 445566",
    farmLocation: "Dinajpur, Birampur",
    variety: "BRRI dhan-49",
    quantityKg: 1750,
    testingLabLocation: "Dinajpur Grain Testing Lab",
    requestedAt: "2026-09-18",
    scheduledDate: "2026-09-24",
    status: "completed",
    priority: "normal",
    notes: "Export-destined lot — full residue panel.",
    assignedGrade: "Grade A",
    moistureContentPercent: 12.8,
    moistureStandardThreshold: 14,
    foreignMatterPercent: 0.5,
    aflatoxinPpm: 0.9,
    complianceVerdict: "Passed",
    visualCondition: "Excellent",
    recommendedAction: "Release for export packing.",
    findings: "Uniform grain size, no live infestation, kernel colour within specification.",
    inspectionDate: "2026-09-24",
    certificateNumber: "QC-26-4821",
    submittedAt: "2026-09-24",
  },
  {
    batchCode: "HB-2026-007",
    produceType: "Tomato",
    farmerName: "Hasina Akter",
    farmerPhone: "+880 1844 209988",
    farmLocation: "Rangpur, Pirganj",
    variety: "Mintoo Super",
    quantityKg: 940,
    testingLabLocation: "Rangpur Post-Harvest Lab",
    requestedAt: "2026-09-20",
    scheduledDate: "2026-09-26",
    status: "completed",
    priority: "normal",
    notes: "",
    assignedGrade: "Grade B",
    moistureContentPercent: 15.1,
    moistureStandardThreshold: 14,
    foreignMatterPercent: 1.6,
    aflatoxinPpm: 1.4,
    complianceVerdict: "Conditional Pass",
    visualCondition: "Fair",
    recommendedAction: "Sort out split fruit and move to a domestic buyer.",
    findings: "Slightly above the moisture threshold; no mould, but 6% of the crate is split.",
    inspectionDate: "2026-09-26",
    certificateNumber: "QC-26-4827",
    submittedAt: "2026-09-26",
  },
  {
    batchCode: "HB-2026-009",
    produceType: "Turmeric",
    farmerName: "Prakash Chandra",
    farmerPhone: "+880 1611 305577",
    farmLocation: "Bogura, Shibganj",
    variety: "Local Red",
    quantityKg: 470,
    testingLabLocation: "Bogura Regional Grain Testing Lab",
    requestedAt: "2026-09-22",
    scheduledDate: "2026-09-29",
    status: "completed",
    priority: "normal",
    notes: "Rejected lot — retest after sun-drying.",
    assignedGrade: "Rejected",
    moistureContentPercent: 18.4,
    moistureStandardThreshold: 12,
    foreignMatterPercent: 4.8,
    aflatoxinPpm: 21.6,
    complianceVerdict: "Rejected",
    visualCondition: "Poor",
    recommendedAction: "Reject the lot; advise re-drying and re-submission.",
    findings: "Moisture and aflatoxin both far outside specification; visible mould on two samples.",
    inspectionDate: "2026-09-29",
    certificateNumber: "QC-26-4833",
    submittedAt: "2026-09-29",
  },
];

module.exports = { inspections };
