/**
 * Reference & administrative seed records.
 * These power catalog/advisory/oversight screens that have no creation UI, so
 * they are bootstrapped once into MongoDB and then fully manageable from the
 * admin portal (status changes, approvals, resolutions, edits).
 */

const masterCrops = [
  {
    cropName: "Boro Rice",
    scientificName: "Oryza sativa",
    category: "Cereal",
    recommendedSeason: "Rabi (Winter - Dec to May)",
    optimalSoilPhRange: "5.5 - 6.8",
    minRainfallMm: 1000,
    maxRainfallMm: 1500,
    averageMaturityDays: 145,
    standardYieldKgPerAcre: 2400,
    benchmarkPriceBdtPerKg: 32,
    approvedVarieties: ["BRRI Dhan-28", "BRRI Dhan-29", "BRRI Dhan-89", "Bangabandhu Dhan-100"],
    pestVulnerabilities: ["Stem Borer", "Brown Planthopper (BPH)", "Bacterial Leaf Blight"],
  },
  {
    cropName: "Aman Rice",
    scientificName: "Oryza sativa var. aman",
    category: "Cereal",
    recommendedSeason: "Kharif-2 (Monsoon - Jul to Nov)",
    optimalSoilPhRange: "5.8 - 7.0",
    minRainfallMm: 1200,
    maxRainfallMm: 2000,
    averageMaturityDays: 135,
    standardYieldKgPerAcre: 2100,
    benchmarkPriceBdtPerKg: 30,
    approvedVarieties: ["BRRI Dhan-49", "BRRI Dhan-71", "BRRI Dhan-87", "Binadhan-17"],
    pestVulnerabilities: ["Sheath Blight", "False Smut", "Leaf Folder"],
  },
  {
    cropName: "Winter Potato (Diamant & Cardinal)",
    scientificName: "Solanum tuberosum",
    category: "Vegetable",
    recommendedSeason: "Rabi (Winter - Nov to Feb)",
    optimalSoilPhRange: "5.2 - 6.5",
    minRainfallMm: 400,
    maxRainfallMm: 600,
    averageMaturityDays: 90,
    standardYieldKgPerAcre: 10500,
    benchmarkPriceBdtPerKg: 18,
    approvedVarieties: ["Diamant", "Cardinal", "Asterix", "BARI Alu-7"],
    pestVulnerabilities: ["Late Blight (Phytophthora)", "Potato Tuber Moth", "Scab"],
  },
  {
    cropName: "Mustard / Rapeseed",
    scientificName: "Brassica campestris",
    category: "Oilseed",
    recommendedSeason: "Rabi (Winter - Oct to Jan)",
    optimalSoilPhRange: "6.0 - 7.5",
    minRainfallMm: 300,
    maxRainfallMm: 500,
    averageMaturityDays: 85,
    standardYieldKgPerAcre: 750,
    benchmarkPriceBdtPerKg: 95,
    approvedVarieties: ["BARI Sarisha-14", "BARI Sarisha-17", "Binasharisha-9"],
    pestVulnerabilities: ["Mustard Aphid", "Alternaria Blight"],
  },
  {
    cropName: "Summer Maize / Corn",
    scientificName: "Zea mays",
    category: "Cereal",
    recommendedSeason: "Kharif-1 (Feb to Jun)",
    optimalSoilPhRange: "6.0 - 7.2",
    minRainfallMm: 600,
    maxRainfallMm: 900,
    averageMaturityDays: 130,
    standardYieldKgPerAcre: 3800,
    benchmarkPriceBdtPerKg: 26,
    approvedVarieties: ["NK-40", "Pacific-984", "BARI Maize-9", "Super Shine-27"],
    pestVulnerabilities: ["Fall Armyworm", "Stem Borer"],
  },
];

const advisories = [
  {
    title: "Brown Planthopper (BPH) Outbreak Alert in Bogura & Naogaon",
    targetCrops: ["Boro Rice", "Aman Rice"],
    targetDistricts: ["Bogura", "Naogaon", "Joypurhat"],
    severity: "high",
    category: "Pest Alert",
    issueDate: "2026-03-15",
    validUntil: "2026-03-30",
    advisoryText:
      "High relative humidity (82%) coupled with elevated night temperatures has accelerated BPH hopper burn across late vegetative paddy plots. Field scouting mandatory at base of stems.",
    recommendedTreatments: [
      "Drain standing water from plots for 3 days to eliminate micro-humidity",
      "Spray Pymetrozine 50 WDG @ 0.6g/L or Dinotefuran 20 SG @ 0.4g/L directly targeting paddy stem base",
      "Avoid excessive synthetic Nitrogen application which triggers succulent vegetative growth",
    ],
    issuingAuthority: "DAE Regional Plant Quarantine & Protection Wing",
  },
  {
    title: "Late Blight Preventive Fungicide Protocol for Commercial Potato",
    targetCrops: ["Winter Potato (Diamant & Cardinal)"],
    targetDistricts: ["Rangpur", "Dinajpur", "Bogura", "Munshiganj"],
    severity: "medium",
    category: "Pest Alert",
    issueDate: "2026-03-10",
    validUntil: "2026-04-05",
    advisoryText:
      "Persistent early morning fog followed by cloudy afternoons creates conditions for Phytophthora infestans zoospore germination.",
    recommendedTreatments: [
      "Prophylactic contact spray with Mancozeb 75 WP @ 2.5g/L",
      "If lesions appear on leaf tips, switch to systemic Cymoxanil + Mancozeb @ 2g/L",
    ],
    issuingAuthority: "Bangladesh Agricultural Research Institute (BARI)",
  },
];

const marketPrices = [
  {
    commodityName: "Boro Paddy (Dry Standard 14% Moisture)",
    variety: "BRRI Dhan-28",
    marketLocation: "Fateh Ali Bazar, Bogura",
    division: "Rajshahi",
    wholesaleMinPriceBdt: 31.5,
    wholesaleMaxPriceBdt: 34.0,
    wholesaleModalPriceBdt: 33.0,
    retailPriceBdt: 37.0,
    priceTrend: "up",
    recordedDate: "2026-03-17",
    volumeTradedMetricTons: 1450,
  },
  {
    commodityName: "Boro Paddy (Aromatic / Super Fine)",
    variety: "Kataribhog / BRRI Dhan-34",
    marketLocation: "Dinajpur Sadar Mokam",
    division: "Rangpur",
    wholesaleMinPriceBdt: 62.0,
    wholesaleMaxPriceBdt: 68.0,
    wholesaleModalPriceBdt: 65.0,
    retailPriceBdt: 74.0,
    priceTrend: "stable",
    recordedDate: "2026-03-17",
    volumeTradedMetricTons: 420,
  },
  {
    commodityName: "Commercial White Potato",
    variety: "Diamant Table Potato",
    marketLocation: "Sherpur Cold Storage Hub, Bogura",
    division: "Rajshahi",
    wholesaleMinPriceBdt: 18.0,
    wholesaleMaxPriceBdt: 21.0,
    wholesaleModalPriceBdt: 19.5,
    retailPriceBdt: 26.0,
    priceTrend: "down",
    recordedDate: "2026-03-17",
    volumeTradedMetricTons: 3200,
  },
  {
    commodityName: "Mustard Seeds (High Oil 42%)",
    variety: "BARI Sarisha-14",
    marketLocation: "Sirajganj Railway Mokam",
    division: "Rajshahi",
    wholesaleMinPriceBdt: 94.0,
    wholesaleMaxPriceBdt: 102.0,
    wholesaleModalPriceBdt: 98.0,
    retailPriceBdt: 110.0,
    priceTrend: "up",
    recordedDate: "2026-03-17",
    volumeTradedMetricTons: 680,
  },
];

const farmVerifications = [
  {
    farmerId: "USR-101",
    farmerName: "Mohiuddin Khan",
    farmName: "Al-Madina Agro Complex",
    division: "Rajshahi",
    district: "Bogura",
    upazila: "Sherpur",
    totalAcreage: 18.5,
    cadastralPlotNumbers: "Plot 412, 413, 415/B",
    mouzaKhatianNumber: "Khatian 882, Mouza Chalk-Paharpur",
    submissionDate: "2026-03-12",
    status: "pending",
    evidenceDocuments: [
      { name: "Land Registration Porcha (Deed)", type: "PDF", url: "/docs/deed-882.pdf" },
      { name: "DAE Union Cadastral Map", type: "JPG", url: "/docs/map-sherpur.jpg" },
      { name: "National ID Card Copy", type: "PDF", url: "/docs/nid-mohiuddin.pdf" },
    ],
  },
  {
    farmerId: "USR-104",
    farmerName: "Abdul Malek Sarker",
    farmName: "Padma Delta Organic Green",
    division: "Dhaka",
    district: "Manikganj",
    upazila: "Singair",
    totalAcreage: 12.0,
    cadastralPlotNumbers: "Plot 108, 109, 110",
    mouzaKhatianNumber: "Khatian 304, Mouza Char-Singair",
    submissionDate: "2026-03-14",
    status: "verified",
    assignedOfficerName: "Nasreen Akhter",
    officerNotes:
      "Land records verified against Upazila Land Registry. GPS coordinates validated on GIS map.",
    evidenceDocuments: [
      { name: "Upazila Land Revenue Dakhila", type: "PDF", url: "/docs/dakhila-304.pdf" },
    ],
  },
  {
    farmerId: "USR-105",
    farmerName: "Fazlur Rahman",
    farmName: "Barendra High-Yield Farm",
    division: "Rajshahi",
    district: "Naogaon",
    upazila: "Badalgachhi",
    totalAcreage: 24.2,
    cadastralPlotNumbers: "Plot 77, 78, 80",
    mouzaKhatianNumber: "Khatian 1192",
    submissionDate: "2026-03-16",
    status: "pending",
    evidenceDocuments: [
      { name: "Khatian 1192 Verified Copy", type: "PDF", url: "/docs/khatian-1192.pdf" },
    ],
  },
];

const auditLogs = [
  {
    timestamp: "2026-03-17 14:32:10 BST",
    actorName: "Mohiuddin Khan",
    actorRole: "Farmer",
    actionType: "HARVEST_LOT_RECORDED",
    targetEntity: "HarvestRecord",
    entityId: "HARV-2026-01",
    ipAddress: "103.14.88.21",
    status: "success",
    details: "Logged 4,200 kg Boro Paddy harvest batch at Sherpur Grain Silo B3",
  },
  {
    timestamp: "2026-03-17 12:15:45 BST",
    actorName: "Nasreen Akhter",
    actorRole: "Extension Officer",
    actionType: "FARM_CADASTRAL_VERIFIED",
    targetEntity: "FarmVerification",
    entityId: "FVR-2026-02",
    ipAddress: "119.30.34.112",
    status: "success",
    details: "Verified cadastral deed 304 for farmer Abdul Malek Sarker (12 acres)",
  },
  {
    timestamp: "2026-03-17 10:04:18 BST",
    actorName: "Admin Security System",
    actorRole: "Automated Daemon",
    actionType: "COLD_CHAIN_ALERT_TRIGGERED",
    targetEntity: "LogisticsFleet",
    entityId: "FLEET-03",
    ipAddress: "10.0.4.18",
    status: "warning",
    details: "Temperature sensor in Van DHA-11-9021 exceeded threshold (+14.2°C)",
  },
  {
    timestamp: "2026-03-17 08:30:00 BST",
    actorName: "Dr. Shahinur Alam",
    actorRole: "Agronomist",
    actionType: "ADVISORY_BROADCAST",
    targetEntity: "AgronomicAdvisory",
    entityId: "ADV-2026-01",
    ipAddress: "103.205.71.4",
    status: "success",
    details: "Dispatched BPH hopper burn alert across Bogura and Naogaon districts",
  },
];

module.exports = { masterCrops, advisories, marketPrices, farmVerifications, auditLogs };
