const express = require("express");
const { validationResult } = require("express-validator");
const auth = require("../../middleware/auth.middleware");
const role = require("../../middleware/role.middleware");
const Demand = require("../../database/models/Demand");
const { mapBuyerDemand } = require("../../utils/domainMaps");
const { logAudit } = require("../../utils/audit");
const { demandRules } = require("../buyer/buyer.validation");

const isAdmin = (user) =>
  !!user &&
  (user.role === "admin" || (Array.isArray(user.roles) && user.roles.includes("admin")));

const httpError = (message, statusCode) => {
  const err = new Error(message);
  err.statusCode = statusCode;
  return err;
};

const throwIfInvalid = (req) => {
  const result = validationResult(req);
  if (result.isEmpty()) return;
  const err = new Error(result.array().map((e) => e.msg).join("; "));
  err.statusCode = 400;
  throw err;
};

const toShape = (doc) =>
  mapBuyerDemand(doc, doc.buyer && doc.buyer.name ? doc.buyer.name : "");

/**
 * Demand board.
 *
 * The access model differs per role, which is why this is hand-written rather
 * than generated by `crudFactory` (that factory always pins non-admins to
 * `ownerKey`, which would hide the open board from the very farmers who need
 * to answer it):
 *
 *   anyone   → the public board (demands still open to an answer), so
 *              `/marketplace/demands` works for anonymous visitors
 *   `mine=1` → their own demands, any status (requires a session)
 *   admin    → everything, and may filter with `?status=`
 *
 * `?status=` from a non-admin is constrained to the board's own statuses, so
 * it cannot be used to probe another buyer's already-fulfilled demands. The
 * write routes below all carry their own `auth` guard.
 */
function buildScope(req) {
  const { user, query } = req;
  const BOARD_STATUSES = ["open", "matched"];

  if (query.mine === "1") {
    if (!user) throw httpError("Sign in to view your own demands", 401);
    const mine = { buyer: user.id };
    return query.status ? { ...mine, status: String(query.status) } : mine;
  }

  if (user && isAdmin(user)) {
    return query.status ? { status: String(query.status) } : {};
  }

  const wanted = query.status ? String(query.status) : "";
  if (wanted && BOARD_STATUSES.includes(wanted)) return { status: wanted };
  return { status: { $in: BOARD_STATUSES } };
}

const router = express.Router();

router.get("/", async (req, res, next) => {
  try {
    const docs = await Demand.find(buildScope(req))
      .sort({ createdAt: -1, _id: -1 })
      .populate("buyer", "name");
    res.json(docs.map(toShape));
  } catch (err) {
    next(err);
  }
});

router.get("/:id", async (req, res, next) => {
  try {
    const doc = await Demand.findById(req.params.id).populate("buyer", "name");
    if (!doc) throw httpError("Demand not found", 404);

    const uid = req.user ? String(req.user.id) : "";
    const ownerDoc = doc.buyer ? String(doc.buyer._id || doc.buyer) : "";
    const owns = !!uid && !!ownerDoc && ownerDoc === uid;
    const boardVisible = ["open", "matched"].includes(String(doc.status));

    // A settled demand belongs to its buyer; 404 rather than 403 so its
    // existence is not disclosed to anonymous visitors.
    if (!isAdmin(req.user) && !owns && !boardVisible) {
      throw httpError("Demand not found", 404);
    }

    res.json(toShape(doc));
  } catch (err) {
    next(err);
  }
});

// `demandRules` is a factory: it must be CALLED (it returns the array of
// chains). Passing the function itself makes Express invoke it as middleware,
// which never calls next() and hangs the request.
router.post(
  "/",
  auth,
  role(["buyer", "admin"]),
  ...demandRules(),
  async (req, res, next) => {
  try {
    throwIfInvalid(req);

    const body = req.body || {};
    const doc = await Demand.create({
      buyer: req.user.id,
      buyerName: req.user.name || "",
      product: body.product,
      quantity: body.quantity,
      unit: body.unit || "kg",
      variety: body.variety || "",
      qualityGrade: body.qualityGrade || "Any",
      maxPricePerKgBdt: body.maxPricePerKgBdt || 0,
      preferredLocation: body.preferredLocation || "",
      deliveryMethod: body.deliveryMethod === "pickup" ? "pickup" : "delivery",
      description: body.description || "",
      qualityRequirements: body.qualityRequirements || "",
      deliveryRequirements: body.deliveryRequirements || "",
      deadline: body.deadline || null,
      status: "open",
      matchedFarmers: 0,
    });

    await logAudit({
      req,
      action: "CREATE",
      entity: "Demand",
      entityId: String(doc._id),
      details: `Posted demand for ${body.quantity} kg ${body.product}`,
    });

    res.status(201).json(toShape(doc));
  } catch (err) {
    next(err);
  }
});

/**
 * Partial edits must not require the whole body. `demandRules()` is a factory,
 * so each call yields fresh chains — mapping `.optional()` over that fresh
 * array cannot bleed back into the POST rules the way a shared array would.
 */
router.put(
  "/:id",
  auth,
  role(["buyer", "admin"]),
  demandRules().map((rule) => rule.optional()),
  async (req, res, next) => {
  try {
    throwIfInvalid(req);

    const doc = await Demand.findById(req.params.id);
    if (!doc) throw httpError("Demand not found", 404);

    const owns = String(doc.buyer) === String(req.user.id);
    if (!owns && !isAdmin(req.user)) {
      throw httpError("You do not have permission to edit this demand", 403);
    }

    const body = req.body || {};
    const allowed = [
      "product",
      "quantity",
      "unit",
      "variety",
      "qualityGrade",
      "maxPricePerKgBdt",
      "preferredLocation",
      "deliveryMethod",
      "description",
      "qualityRequirements",
      "deliveryRequirements",
      "deadline",
    ];

    // Only an admin may close out someone else's demand.
    if (isAdmin(req.user) && body.status) {
      doc.status = body.status;
      if (body.matchedFarmers !== undefined) doc.matchedFarmers = body.matchedFarmers;
    }

    allowed.forEach((key) => {
      if (body[key] !== undefined && body[key] !== null) doc[key] = body[key];
    });

    await doc.save();

    await logAudit({
      req,
      action: "UPDATE",
      entity: "Demand",
      entityId: String(doc._id),
      details: `Updated demand for ${doc.product}`,
    });

    res.json(toShape(doc));
  } catch (err) {
    next(err);
  }
});

/** Farmer indicates they can supply this demand. */
router.post("/:id/respond", auth, role(["farmer", "admin"]), async (req, res, next) => {
  try {
    const doc = await Demand.findById(req.params.id);
    if (!doc) throw httpError("Demand not found", 404);
    if (!["open", "matched"].includes(String(doc.status))) {
      throw httpError("This demand is no longer accepting responses", 409);
    }

    doc.matchedFarmers = (Number(doc.matchedFarmers) || 0) + 1;
    if (doc.status === "open") doc.status = "matched";
    await doc.save();

    res.json(toShape(doc));
  } catch (err) {
    next(err);
  }
});

router.delete("/:id", auth, async (req, res, next) => {
  try {
    const doc = await Demand.findById(req.params.id);
    if (!doc) throw httpError("Demand not found", 404);

    const owns = String(doc.buyer) === String(req.user.id);
    if (!owns && !isAdmin(req.user)) {
      throw httpError("You do not have permission to delete this demand", 403);
    }

    await doc.deleteOne();

    await logAudit({
      req,
      action: "DELETE",
      entity: "Demand",
      entityId: String(doc._id),
      details: `Removed demand for ${doc.product}`,
    });

    res.json({ success: true, id: String(doc._id) });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
